const mockMoviesShowingPg1 = [
  {
    adult: false,
    backdrop_path: '',
    genre_ids: [12],
    id: 1,
    original_language: '',
    original_title: '',
    overview: 'Movie 1',
    popularity: 1,
    poster_path: '/1.jpg',
    release_date: '2020-01-01',
    title: 'Movie 1',
    video: false,
    vote_average: 1,
    vote_count: 1
  },
  {
    adult: false,
    backdrop_path: '',
    genre_ids: [12],
    id: 2,
    original_language: '',
    original_title: '',
    overview: 'Movie 2',
    popularity: 2,
    poster_path: '/2.jpg',
    release_date: '2020-01-02',
    title: 'Movie 2',
    video: false,
    vote_average: 2,
    vote_count: 2
  },
  {
    adult: false,
    backdrop_path: '',
    genre_ids: [12],
    id: 3,
    original_language: '',
    original_title: '',
    overview: 'Movie 3',
    popularity: 3,
    poster_path: '/3.jpg',
    release_date: '2020-01-03',
    title: 'Movie 3',
    video: false,
    vote_average: 3,
    vote_count: 3
  },
  {
    adult: false,
    backdrop_path: '',
    genre_ids: [12],
    id: 4,
    original_language: '',
    original_title: '',
    overview: 'Movie 4',
    popularity: 4,
    poster_path: '/4.jpg',
    release_date: '2020-01-04',
    title: 'Movie 4',
    video: false,
    vote_average: 4,
    vote_count: 4
  },
  {
    adult: false,
    backdrop_path: '',
    genre_ids: [12],
    id: 5,
    original_language: '',
    original_title: '',
    overview: 'Movie 5',
    popularity: 5,
    poster_path: '/5.jpg',
    release_date: '2020-01-05',
    title: 'Movie 5',
    video: false,
    vote_average: 5,
    vote_count: 5
  },
  {
    adult: false,
    backdrop_path: '',
    genre_ids: [12],
    id: 6,
    original_language: '',
    original_title: '',
    overview: 'Movie 6',
    popularity: 6,
    poster_path: '/6.jpg',
    release_date: '2020-01-06',
    title: 'Movie 6',
    video: false,
    vote_average: 6,
    vote_count: 6
  },
  {
    adult: false,
    backdrop_path: '',
    genre_ids: [12],
    id: 7,
    original_language: '',
    original_title: '',
    overview: 'Movie 7',
    popularity: 7,
    poster_path: '/7.jpg',
    release_date: '2020-01-07',
    title: 'Movie 7',
    video: false,
    vote_average: 7,
    vote_count: 7
  },
  {
    adult: false,
    backdrop_path: '',
    genre_ids: [12],
    id: 8,
    original_language: '',
    original_title: '',
    overview: 'Movie 8',
    popularity: 8,
    poster_path: '/8.jpg',
    release_date: '2020-01-08',
    title: 'Movie 8',
    video: false,
    vote_average: 8,
    vote_count: 8
  },
  {
    adult: false,
    backdrop_path: '',
    genre_ids: [12],
    id: 9,
    original_language: '',
    original_title: '',
    overview: 'Movie 9',
    popularity: 9,
    poster_path: '/9.jpg',
    release_date: '2020-01-09',
    title: 'Movie 9',
    video: false,
    vote_average: 9,
    vote_count: 9
  },
  {
    adult: false,
    backdrop_path: '',
    genre_ids: [12],
    id: 10,
    original_language: '',
    original_title: '',
    overview: 'Movie 10',
    popularity: 10,
    poster_path: '/10.jpg',
    release_date: '2020-01-10',
    title: 'Movie 10',
    video: false,
    vote_average: 10,
    vote_count: 10
  },
  {
    adult: false,
    backdrop_path: '',
    genre_ids: [14],
    id: 11,
    original_language: '',
    original_title: '',
    overview: 'Movie 11',
    popularity: 11,
    poster_path: '/11.jpg',
    release_date: '2020-01-11',
    title: 'Movie 11',
    video: false,
    vote_average: 11,
    vote_count: 11
  },
  {
    adult: false,
    backdrop_path: '',
    genre_ids: [14],
    id: 12,
    original_language: '',
    original_title: '',
    overview: 'Movie 12',
    popularity: 12,
    poster_path: '/12.jpg',
    release_date: '2020-01-12',
    title: 'Movie 12',
    video: false,
    vote_average: 12,
    vote_count: 12
  },
  {
    adult: false,
    backdrop_path: '',
    genre_ids: [14],
    id: 13,
    original_language: '',
    original_title: '',
    overview: 'Movie 13',
    popularity: 13,
    poster_path: '/13.jpg',
    release_date: '2020-01-13',
    title: 'Movie 13',
    video: false,
    vote_average: 13,
    vote_count: 13
  },
  {
    adult: false,
    backdrop_path: '',
    genre_ids: [14],
    id: 14,
    original_language: '',
    original_title: '',
    overview: 'Movie 14',
    popularity: 14,
    poster_path: '/14.jpg',
    release_date: '2020-01-14',
    title: 'Movie 14',
    video: false,
    vote_average: 14,
    vote_count: 14
  },
  {
    adult: false,
    backdrop_path: '',
    genre_ids: [14],
    id: 15,
    original_language: '',
    original_title: '',
    overview: 'Movie 15',
    popularity: 15,
    poster_path: '/15.jpg',
    release_date: '2020-01-15',
    title: 'Movie 15',
    video: false,
    vote_average: 15,
    vote_count: 15
  },
  {
    adult: false,
    backdrop_path: '',
    genre_ids: [14],
    id: 16,
    original_language: '',
    original_title: '',
    overview: 'Movie 16',
    popularity: 16,
    poster_path: '/16.jpg',
    release_date: '2020-01-16',
    title: 'Movie 16',
    video: false,
    vote_average: 16,
    vote_count: 16
  },
  {
    adult: false,
    backdrop_path: '',
    genre_ids: [14],
    id: 17,
    original_language: '',
    original_title: '',
    overview: 'Movie 17',
    popularity: 17,
    poster_path: '/17.jpg',
    release_date: '2020-01-17',
    title: 'Movie 17',
    video: false,
    vote_average: 17,
    vote_count: 17
  },
  {
    adult: false,
    backdrop_path: '',
    genre_ids: [14],
    id: 18,
    original_language: '',
    original_title: '',
    overview: 'Movie 18',
    popularity: 18,
    poster_path: '/18.jpg',
    release_date: '2020-01-18',
    title: 'Movie 18',
    video: false,
    vote_average: 18,
    vote_count: 18
  },
  {
    adult: false,
    backdrop_path: '',
    genre_ids: [14],
    id: 19,
    original_language: '',
    original_title: '',
    overview: 'Movie 19',
    popularity: 19,
    poster_path: '/19.jpg',
    release_date: '2020-01-19',
    title: 'Movie 19',
    video: false,
    vote_average: 19,
    vote_count: 19
  },
  {
    adult: false,
    backdrop_path: '',
    genre_ids: [12, 14],
    id: 20,
    original_language: '',
    original_title: '',
    overview: 'Movie 20',
    popularity: 20,
    poster_path: '/20.jpg',
    release_date: '2020-01-20',
    title: 'Movie 20',
    video: false,
    vote_average: 20,
    vote_count: 20
  }
];

export default mockMoviesShowingPg1;
